import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Part 1: Foundations of Physical AI',
      link: {
        type: 'generated-index',
        title: 'Foundations of Physical AI'
      },
      items: [{ type: 'autogenerated', dirName: 'part1-foundations' }],
    },
    {
      type: 'category',
      label: 'Part 2: The Robotic Nervous System – ROS 2',
      link: {
        type: 'generated-index',
        title: 'The Robotic Nervous System – ROS 2'
      },
      items: [
        'part2-ros2/quickstart',
        'part2-ros2/chapter4-ros2-architecture',
        'part2-ros2/chapter5-packages',
        'part2-ros2/chapter6-advanced-concepts',
        'part2-ros2/chapter7-python-agents',
      ],
    },
    {
      type: 'category',
      label: 'Part 3: Robot Description and Modeling',
      link: {
        type: 'generated-index',
        title: 'Robot Description and Modeling'
      },
      items: [
        'part3-robot-modeling/quickstart',
        'part3-robot-modeling/chapter8-urdf',
        'part3-robot-modeling/chapter9-sdf-usd',
        'part3-robot-modeling/chapter10-kinematics-dynamics',
      ],
    },
    {
      type: 'category',
      label: 'Part 4: The Digital Twin – Simulation',
      link: {
        type: 'generated-index',
        title: 'The Digital Twin – Simulation'
      },
      items: [{ type: 'autogenerated', dirName: 'part4-digital-twin-simulation' }],
    },
    {
      type: 'category',
      label: 'Part 5: The AI-Robot Brain - NVIDIA Isaac',
      link: {
        type: 'generated-index',
        title: 'The AI-Robot Brain - NVIDIA Isaac'
      },
      items: [{ type: 'autogenerated', dirName: 'part5-nvidia-isaac' }],
    },
    {
      type: 'category',
      label: 'Part 6: Vision-Language-Action (VLA) Systems',
      link: {
        type: 'generated-index',
        title: 'Vision-Language-Action (VLA) Systems'
      },
      items: [{ type: 'autogenerated', dirName: 'part6-vla-systems' }],
    },
    {
      type: 'category',
      label: 'Part 7: Conversational Robotics',
      link: {
        type: 'generated-index',
        title: 'Conversational Robotics'
      },
      items: [{ type: 'autogenerated', dirName: 'part7-conversational-robotics' }],
    },
    {
      type: 'category',
      label: 'Part 8: Humanoid Robot Development',
      link: {
        type: 'generated-index',
        title: 'Humanoid Robot Development'
      },
      items: [{ type: 'autogenerated', dirName: 'part8-humanoid-robot-development' }],
    },
    {
      type: 'category',
      label: 'Part 9: Integration and Capstone Project',
      link: {
        type: 'generated-index',
        title: 'Integration and Capstone Project'
      },
      items: [
        'part9-integration-and-capstone-project/quickstart',
        'part9-integration-and-capstone-project/chapter37-full-stack-integration',
        'part9-integration-and-capstone-project/chapter38-sim-to-real-transfer',
        'part9-integration-and-capstone-project/chapter39-testing-validation-deployment',
        'part9-integration-and-capstone-project/chapter40-autonomous-humanoid-capstone-project',
      ],
    },
    {
      type: 'category',
      label: 'Part 10: Advanced Topics and Future Directions',
      link: {
        type: 'generated-index',
        title: 'Advanced Topics and Future Directions'
      },
      items: [{ type: 'autogenerated', dirName: 'part10-advanced-topics-future-directions' }],
    },
  ],
};

export default sidebars;